plugins {
id 'com.android.application'
}

android {
namespace "onetry.towipe"
compileSdk 35

lint {
        checkReleaseBuilds false
    }

defaultConfig {  
    applicationId "onetry.towipe"  
    minSdk 29
    targetSdk 37
    versionCode 1
    versionName "1.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
         }  
}

}

dependencies {}
